env:
  browser: true
  commonjs: true
  es2021: true
  jest: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: 13
rules:
  linebreak-style:
    - warn
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  eqeqeq:
    - error
  no-trailing-spaces:
    - warn
  object-curly-spacing:
    - error
    - always
  arrow-spacing:
    - error
    - { before: true, after: true }
